name: Deploy to Server

on:
  push:
    branches:
      - to-vue

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run tests
        run: yarn test

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Remove old Docker container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: docker rm -f drawga || true

      - name: Remove old Docker image
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: docker rmi ${{ secrets.DOCKER_HUB_USERNAME }}/drawga:latest || true

      - name: Pull new Docker image
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/drawga:latest

      - name: Run new Docker container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            docker run --network drawga --name drawga \
              -v /home/drawga-saves:/app/saves \
              -d ${{ secrets.DOCKER_HUB_USERNAME }}/drawga:latest
